services:
  webapp_a:
    build: .
    command: "--addrport 8000 -- Hello from a"
    ports:
      - "8000:8000"
  webapp_b:
    build: .
    command: "--addrport 8001 -- Hello from b"
    ports:
      - "8001:8001"
  router:
    image: nginx:latest
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "1234:1234"
    depends_on:
      - webapp_a
      - webapp_b
    expose:
    - "1234"